require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sellers", type: :request do
  let(:trade_partner) { FactoryBot.create(:trade_partner) }
  let(:user) { FactoryBot.create(:user) }

  before do
    allow_any_instance_of(ApplicationController).to receive(:current_user) { user }
  end
  # This should return the minimal set of attributes required to create a valid
  # Seller. As you add validations to Seller, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {trade_partner_id: trade_partner.id}
  }

  let(:invalid_attributes) {
    {trade_partner_id: nil}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Seller.create! valid_attributes
      get sellers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      seller = Seller.create! valid_attributes
      get seller_url(seller, format: :json)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_seller_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      seller = Seller.create! valid_attributes
      get edit_seller_url(seller)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Seller" do
        expect {
          post sellers_url, params: {seller: valid_attributes}
        }.to change(Seller, :count).by(1)
      end

      it "redirects to the created seller" do
        post sellers_url, params: {seller: valid_attributes}
        expect(response).to redirect_to(edit_seller_url(Seller.last, locale: :en))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Seller" do
        expect {
          post sellers_url, params: {seller: invalid_attributes}
        }.to change(Seller, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sellers_url, params: {seller: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    let(:other_trade_partner) { FactoryBot.create(:trade_partner) }
    context "with valid parameters" do
      let(:new_attributes) {
        {trade_partner_id: other_trade_partner.id}
      }

      it "updates the requested seller" do
        seller = Seller.create! valid_attributes
        patch seller_url(seller), params: {seller: new_attributes}
        seller.reload
        expect(seller.trade_partner).to eq(other_trade_partner)
      end

      it "redirects to the seller" do
        seller = Seller.create! valid_attributes
        patch seller_url(seller), params: {seller: new_attributes}
        seller.reload
        expect(response).to redirect_to(edit_seller_url(seller, locale: :en))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        seller = Seller.create! valid_attributes
        patch seller_url(seller), params: {seller: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested seller" do
      seller = Seller.create! valid_attributes
      expect {
        delete seller_url(seller)
      }.to change(Seller, :count).by(-1)
    end

    it "redirects to the sellers list" do
      seller = Seller.create! valid_attributes
      delete seller_url(seller)
      expect(response).to redirect_to(sellers_url(locale: :en))
    end
  end
end
