require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trade_partners", type: :request do
  let(:user) { FactoryBot.create(:user) }

  before do
    allow_any_instance_of(ApplicationController).to receive(:current_user) { user }
  end

  # This should return the minimal set of attributes required to create a valid
  # TradePartner. As you add validations to TradePartner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.attributes_for(:trade_partner, :minimal)
  }

  let(:invalid_attributes) {
    FactoryBot.attributes_for(:trade_partner, :minimal, name: nil)
  }

  describe "GET /index" do
    it "renders a successful response" do
      TradePartner.create! valid_attributes
      get trade_partners_url
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trade_partner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      trade_partner = TradePartner.create! valid_attributes
      get edit_trade_partner_url(trade_partner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TradePartner" do
        expect {
          post trade_partners_url, params: {trade_partner: valid_attributes}
        }.to change(TradePartner, :count).by(1)
      end

      it "redirects to the created trade_partner" do
        post trade_partners_url, params: {trade_partner: valid_attributes}
        expect(response).to redirect_to(trade_partners_url(params: {locale: :en}))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TradePartner" do
        expect {
          post trade_partners_url, params: {trade_partner: invalid_attributes}
        }.to change(TradePartner, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post trade_partners_url, params: {trade_partner: invalid_attributes}
        expect(response).not_to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {name: "New Company"}
      }

      it "updates the requested trade_partner" do
        trade_partner = TradePartner.create! valid_attributes
        patch trade_partner_url(trade_partner), params: {trade_partner: new_attributes}
        trade_partner.reload
        expect(trade_partner.name).to eq("New Company")
      end

      it "redirects to the trade_partner" do
        trade_partner = TradePartner.create! valid_attributes
        patch trade_partner_url(trade_partner), params: {trade_partner: new_attributes}
        trade_partner.reload
        expect(response).to redirect_to(trade_partners_url(locale: :en))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        trade_partner = TradePartner.create! valid_attributes
        patch trade_partner_url(trade_partner), params: {trade_partner: invalid_attributes}
        expect(response).not_to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trade_partner" do
      trade_partner = TradePartner.create! valid_attributes
      expect {
        delete trade_partner_url(trade_partner)
      }.to change(TradePartner, :count).by(-1)
    end

    it "redirects to the trade_partners list" do
      trade_partner = TradePartner.create! valid_attributes
      delete trade_partner_url(trade_partner)
      expect(response).to redirect_to(trade_partners_url(params: {locale: :en}))
    end
  end
end
